"use client";

import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, type Word, type WordSense } from "@/lib/api";
import { useI18n } from "@/lib/i18n";
import { useToast } from "@/lib/toast";
import { errText } from "@/lib/errText";
import { hasTranscription, useShowTranscription } from "@/lib/learnPrefs";
import { cn } from "@/lib/utils";
import { Skeleton } from "@/components/ui/skeleton";
import { TapGlossPills } from "@/components/TapGlossPills";

// Stable empty list so the memo below doesn't re-fire every render.
const NO_SENSES: WordSense[] = [];

const srcFont = (lang: string) => (lang === "zh" || lang === "zh-Hant" || lang === "ja" ? "font-zh" : "");
const tgtFont = (lang: string) => (lang === "zh" || lang === "zh-Hant" ? "font-zh" : "");

// "включить, зажечь; открыть" -> ["включить", "зажечь", "открыть"]
const parts = (s: string | null | undefined) =>
  (s ?? "")
    .split(/[;；,，、/]/)
    .map((x) => x.trim().toLowerCase())
    .filter(Boolean);

// Which senses the card currently tests: those sharing a gloss with meaningZh.
function testedSet(senses: WordSense[], meaning: string | null): Set<number> {
  const card = new Set(parts(meaning));
  const out = new Set<number>();
  senses.forEach((s, i) => {
    if (parts(s.meaning).some((p) => card.has(p))) out.add(i);
  });
  return out;
}

/**
 * Pleco-style "Meanings" block for the word page: numbered senses with part of
 * speech and 1–2 short phrases each. Generated by the model on the first open and
 * cached on the card. The learner ticks which sense(s) the flashcard tests, which
 * rewrites meaningZh. Falls back to the flat collocation chips if senses fail.
 */
export function WordSenses({ word }: { word: Word }) {
  const { t } = useI18n();
  const { show } = useToast();
  const qc = useQueryClient();
  const showTr = useShowTranscription() && hasTranscription(word.sourceLang);
  const cached = word.senses && word.senses.length ? word.senses : null;
  const q = useQuery({
    queryKey: ["senses", word.id, word.word, word.sourceLang, word.targetLang],
    queryFn: () => api.wordSenses(word.id).then((r) => r.senses),
    enabled: !cached,
    staleTime: Infinity,
    retry: 1,
  });
  const senses = cached ?? q.data ?? NO_SENSES;

  const initial = useMemo(() => testedSet(senses, word.meaningZh), [senses, word.meaningZh]);
  const [picked, setPicked] = useState<Set<number>>(initial);
  useEffect(() => setPicked(initial), [initial]);
  const dirty = picked.size !== initial.size || [...picked].some((i) => !initial.has(i));

  const save = useMutation({
    mutationFn: () =>
      api.updateWord(word.id, {
        meaningZh: senses
          .filter((_, i) => picked.has(i))
          .map((s) => s.meaning)
          .join("; "),
      }),
    onSuccess: (w) => {
      qc.setQueryData(["word", word.id], w);
      qc.invalidateQueries({ queryKey: ["words"] });
      show({ icon: "✓", title: t("word.meaningsSaved") });
    },
    onError: (e) => show({ icon: "⚠️", title: errText(e, t) }),
  });

  if (!cached && q.isPending)
    return (
      <div className="space-y-2">
        <p className="text-xs font-semibold uppercase tracking-[0.1em] text-ink-faint">{t("word.meanings")}</p>
        <Skeleton className="h-16 rounded-[18px]" />
        <p className="text-[12px] text-ink-faint">{t("word.meaningsLoading")}</p>
      </div>
    );

  if (!senses.length)
    return word.collocations.length > 0 ? (
      <TapGlossPills
        label={t("word.collocations")}
        items={word.collocations}
        sourceLang={word.sourceLang}
        targetLang={word.targetLang}
      />
    ) : null;

  const multi = senses.length > 1;
  const toggle = (i: number) =>
    setPicked((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i);
      else next.add(i);
      return next;
    });

  return (
    <div className="space-y-2">
      <p className="text-xs font-semibold uppercase tracking-[0.1em] text-ink-faint">{t("word.meanings")}</p>
      <ol className="divide-y divide-black/[0.06] rounded-[18px] border border-black/[0.06] bg-surface">
        {senses.map((s, i) => (
          <li key={i} className={cn("flex gap-3 p-4", multi && picked.has(i) && "bg-sage-tint/40")}>
            {multi && (
              <label className="flex shrink-0 cursor-pointer items-start gap-2 pt-0.5">
                <input
                  type="checkbox"
                  checked={picked.has(i)}
                  onChange={() => toggle(i)}
                  aria-label={s.meaning}
                  className="mt-0.5 h-4 w-4 accent-[#7c9885]"
                />
                <span className="w-4 text-[15px] font-semibold text-ink-faint">{i + 1}</span>
              </label>
            )}
            <div className="min-w-0 flex-1 space-y-1.5">
              <div className="flex flex-wrap items-baseline gap-x-2 gap-y-0.5">
                {s.pos && (
                  <span className="text-[11px] font-semibold uppercase tracking-[0.1em] text-ink-faint">{s.pos}</span>
                )}
                <span className={cn("text-[17px] font-medium text-sage-deep", tgtFont(word.targetLang))}>{s.meaning}</span>
                {multi && initial.has(i) && (
                  <span className="rounded-full bg-sage-tint px-2 py-0.5 text-[11px] font-semibold text-sage-deep">
                    {t("word.meaningsTested")}
                  </span>
                )}
              </div>
              {s.phrases.map((p, j) => (
                <p key={j} className="text-[14px] leading-snug">
                  <span className={cn("text-ink", srcFont(word.sourceLang))}>{p.text}</span>
                  {showTr && p.reading && <span className="ml-1.5 text-ink-faint">{p.reading}</span>}
                  {p.translation && (
                    <span className={cn("text-ink-soft", tgtFont(word.targetLang))}> — {p.translation}</span>
                  )}
                </p>
              ))}
            </div>
          </li>
        ))}
      </ol>
      {multi && (
        <div className="flex flex-wrap items-center gap-3">
          <p className="text-[12px] text-ink-faint">{t("word.meaningsHint")}</p>
          {dirty && (
            <button
              type="button"
              onClick={() => save.mutate()}
              disabled={picked.size === 0 || save.isPending}
              className="rounded-full bg-sage px-3.5 py-1.5 text-xs font-semibold text-white transition-colors hover:bg-sage-deep disabled:opacity-50"
            >
              {t("word.meaningsSave")}
            </button>
          )}
        </div>
      )}
    </div>
  );
}
