"use client";

import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, type Word, type WordSense } from "@/lib/api";
import { useI18n } from "@/lib/i18n";
import { useToast } from "@/lib/toast";
import { errText } from "@/lib/errText";
import { hasTranscription, useShowTranscription } from "@/lib/learnPrefs";
import { cn } from "@/lib/utils";
import { Skeleton } from "@/components/ui/skeleton";
import { TapGlossPills } from "@/components/TapGlossPills";
import { Check, Plus } from "lucide-react";

// Stable empty list so the memo below doesn't re-fire every render.
const NO_SENSES: WordSense[] = [];

const srcFont = (lang: string) => (lang === "zh" || lang === "zh-Hant" || lang === "ja" ? "font-zh" : "");
const tgtFont = (lang: string) => (lang === "zh" || lang === "zh-Hant" ? "font-zh" : "");

// A gloss without its usage hint: "открыть (дверь, книгу)" -> "открыть".
const bare = (s: string) => s.replace(/\s*[(（][^)）]*[)）]/g, "").trim();

// "включить, зажечь; открыть" -> ["включить", "зажечь", "открыть"]
const parts = (s: string | null | undefined) =>
  bare(s ?? "")
    .split(/[;；,，、/]/)
    .map((x) => x.trim().toLowerCase())
    .filter(Boolean);

// Which senses the card currently tests: those sharing a gloss with meaningZh.
// If none match (the card's wording differs, e.g. "открывать" vs "открыть"), fall
// back to the sense the model flagged as the card's own when it generated them.
function testedSet(senses: WordSense[], meaning: string | null): Set<number> {
  const card = new Set(parts(meaning));
  const out = new Set<number>();
  senses.forEach((s, i) => {
    if (parts(s.meaning).some((p) => card.has(p))) out.add(i);
  });
  if (!out.size) senses.forEach((s, i) => s.onCard && out.add(i));
  return out;
}

/**
 * Pleco-style "Meanings" block for the word page: numbered senses with part of
 * speech and two short phrases each. Generated by the model on the first open and
 * cached on the card (server side). The learner picks which sense(s) the
 * flashcard tests, which rewrites meaningZh. Falls back to the collocation chips.
 */
export function WordSenses({ word }: { word: Word }) {
  const { t } = useI18n();
  const { show } = useToast();
  const qc = useQueryClient();
  const showTr = useShowTranscription() && hasTranscription(word.sourceLang);
  const q = useQuery({
    queryKey: ["senses", word.id, word.word, word.sourceLang, word.targetLang],
    queryFn: () => api.wordSenses(word.id).then((r) => r.senses),
    staleTime: Infinity,
    retry: 1,
  });
  const senses = q.data ?? NO_SENSES;

  const initial = useMemo(() => testedSet(senses, word.meaningZh), [senses, word.meaningZh]);
  const [picked, setPicked] = useState<Set<number>>(initial);
  useEffect(() => setPicked(initial), [initial]);
  const dirty = picked.size !== initial.size || [...picked].some((i) => !initial.has(i));

  const save = useMutation({
    mutationFn: () =>
      api.updateWord(word.id, {
        meaningZh: senses
          .filter((_, i) => picked.has(i))
          .map((s) => bare(s.meaning))
          .join("; "),
      }),
    onSuccess: (w) => {
      qc.setQueryData(["word", word.id], w);
      qc.invalidateQueries({ queryKey: ["words"] });
      show({ icon: "✓", title: t("word.meaningsSaved") });
    },
    onError: (e) => show({ icon: "⚠️", title: errText(e, t) }),
  });

  if (q.isPending)
    return (
      <div className="space-y-2">
        <p className="text-xs font-semibold uppercase tracking-[0.1em] text-ink-faint">{t("word.meanings")}</p>
        <Skeleton className="h-24 rounded-[18px]" />
        <p className="text-[12px] text-ink-faint">{t("word.meaningsLoading")}</p>
      </div>
    );

  if (!senses.length)
    return word.collocations.length > 0 ? (
      <TapGlossPills
        label={t("word.collocations")}
        items={word.collocations}
        sourceLang={word.sourceLang}
        targetLang={word.targetLang}
      />
    ) : null;

  const multi = senses.length > 1;
  const toggle = (i: number) =>
    setPicked((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i);
      else next.add(i);
      return next;
    });

  return (
    <div className="space-y-2">
      <p className="text-xs font-semibold uppercase tracking-[0.1em] text-ink-faint">{t("word.meanings")}</p>
      <ol className="overflow-hidden rounded-[18px] border border-black/[0.06] bg-surface">
        {senses.map((s, i) => {
          const on = picked.has(i);
          return (
            <li
              key={i}
              className={cn(
                "flex gap-3 border-black/[0.06] px-4 py-3.5 transition-colors sm:gap-4 sm:px-5 [&:not(:first-child)]:border-t",
                multi && on && "bg-sage-tint/35",
              )}
            >
              {multi && (
                <span
                  className={cn(
                    "mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-[13px] font-bold",
                    on ? "bg-sage text-white" : "bg-black/[0.05] text-ink-soft",
                  )}
                >
                  {i + 1}
                </span>
              )}
              <div className="min-w-0 flex-1">
                <div className="flex items-start justify-between gap-3">
                  <p className="min-w-0 leading-snug">
                    {s.pos && <span className="mr-2 text-[13px] italic text-ink-faint">{s.pos}</span>}
                    <span className={cn("text-[18px] font-semibold text-ink", tgtFont(word.targetLang))}>{s.meaning}</span>
                  </p>
                  {multi && (
                    <button
                      type="button"
                      onClick={() => toggle(i)}
                      aria-pressed={on}
                      className={cn(
                        "inline-flex shrink-0 items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold transition-colors",
                        on
                          ? "bg-sage text-white hover:bg-sage-deep"
                          : "border border-black/[0.1] text-ink-soft hover:border-sage/60 hover:text-sage-deep",
                      )}
                    >
                      {on ? <Check className="h-3 w-3" /> : <Plus className="h-3 w-3" />}
                      {on ? t("word.meaningsTested") : t("word.meaningsAdd")}
                    </button>
                  )}
                </div>
                {s.phrases.length > 0 && (
                  <ul className="mt-2 space-y-1.5 border-l-2 border-sage/30 pl-3">
                    {s.phrases.map((p, j) => (
                      <li key={j} className="leading-snug">
                        <span className={cn("text-[15px] text-ink", srcFont(word.sourceLang))}>{p.text}</span>
                        {showTr && p.reading && <span className="ml-2 text-[13px] text-ink-faint">{p.reading}</span>}
                        {p.translation && (
                          <span className={cn("block text-[13px] text-ink-soft", tgtFont(word.targetLang))}>
                            {p.translation}
                          </span>
                        )}
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            </li>
          );
        })}
      </ol>
      {multi && (
        <div className="flex flex-wrap items-center gap-3">
          <p className="text-[12px] text-ink-faint">{t("word.meaningsHint")}</p>
          {dirty && (
            <button
              type="button"
              onClick={() => save.mutate()}
              disabled={picked.size === 0 || save.isPending}
              className="rounded-full bg-sage px-3.5 py-1.5 text-xs font-semibold text-white transition-colors hover:bg-sage-deep disabled:opacity-50"
            >
              {t("word.meaningsSave")}
            </button>
          )}
        </div>
      )}
    </div>
  );
}
