"use client";

import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, type Word, type WordSense } from "@/lib/api";
import { useI18n } from "@/lib/i18n";
import { useToast } from "@/lib/toast";
import { errText } from "@/lib/errText";
import { hasTranscription, useShowTranscription } from "@/lib/learnPrefs";
import { cn } from "@/lib/utils";
import { Skeleton } from "@/components/ui/skeleton";
import { TapGlossPills } from "@/components/TapGlossPills";
import { Check, Plus } from "lucide-react";

// Stable empty list so the memo below doesn't re-fire every render.
const NO_SENSES: WordSense[] = [];

const srcFont = (lang: string) => (lang === "zh" || lang === "zh-Hant" || lang === "ja" ? "font-zh" : "");
const tgtFont = (lang: string) => (lang === "zh" || lang === "zh-Hant" ? "font-zh" : "");

// A gloss without its usage hint: "открыть (дверь, книгу)" -> "открыть".
const bare = (s: string) => s.replace(/\s*[(（][^)）]*[)）]/g, "").trim();
// Just the usage hint: "открыть (дверь, книгу)" -> "(дверь, книгу)".
const hint = (s: string) => s.match(/[(（][^)）]*[)）]/)?.[0] ?? "";

// "включить, зажечь; открыть" -> ["включить", "зажечь", "открыть"]
const terms = (s: string) =>
  bare(s)
    .split(/[;；,，、/]/)
    .map((x) => x.trim())
    .filter(Boolean);

// Which senses the card tests — the server keeps that on the senses themselves.
const testedSet = (senses: WordSense[]) => new Set(senses.flatMap((s, i) => (s.onCard ? [i] : [])));

/**
 * The card's meaning, written from the picked senses. A term an earlier sense
 * already said is dropped, so Chinese senses that share a head word
 * (指出（错误…）/ 指明，指出（位置…）) read as "指出（错误…）；指明（位置…）" instead of
 * "指出; 指明，指出"; a sense left with nothing of its own keeps its full gloss, so
 * two senses can never collapse into one word. The usage hint always stays: it is
 * what tells "to save (a person, a life)" from saving money.
 */
function composeMeaning(picked: WordSense[], targetLang: string): string {
  const cjk = targetLang === "zh" || targetLang === "zh-Hant" || targetLang === "ja";
  const said = new Set<string>();
  const glosses = picked.map((s) => {
    const all = terms(s.meaning);
    const kept = all.filter((x) => {
      const k = x.toLowerCase();
      if (said.has(k)) return false;
      said.add(k);
      return true;
    });
    if (!kept.length || kept.length === all.length) return s.meaning.trim();
    const h = hint(s.meaning);
    return kept.join(cjk ? "，" : ", ") + (h && !cjk ? " " : "") + h;
  });
  return glosses.join(cjk ? "；" : "; ");
}

/**
 * Pleco-style "Meanings" block for the word page: numbered senses with part of
 * speech and two short phrases each. Generated by the model on the first open and
 * cached on the card (server side). The learner picks which sense(s) the
 * flashcard tests, which rewrites meaningZh. Falls back to the collocation chips.
 */
export function WordSenses({ word }: { word: Word }) {
  const { t } = useI18n();
  const { show } = useToast();
  const qc = useQueryClient();
  const showTr = useShowTranscription() && hasTranscription(word.sourceLang);
  const sensesKey = ["senses", word.id, word.word, word.sourceLang, word.targetLang];
  const q = useQuery({
    queryKey: sensesKey,
    queryFn: () => api.wordSenses(word.id),
    staleTime: Infinity,
    retry: 1,
  });
  const senses = q.data?.senses ?? NO_SENSES;
  const credit = q.data?.credit;

  const initial = useMemo(() => testedSet(senses), [senses]);
  const [picked, setPicked] = useState<Set<number>>(initial);
  useEffect(() => setPicked(initial), [initial]);
  // What the card will say once saved — shown before the save, so "test these"
  // is a promise the learner can read rather than a surprise.
  const indexes = useMemo(() => [...picked].sort((a, b) => a - b), [picked]);
  const preview = composeMeaning(
    indexes.map((i) => senses[i]).filter(Boolean),
    word.targetLang,
  );
  // Older cards say less than the sense they test ("goal" where the sense reads
  // "goal, objective (something aimed at)"): same pick, so offer the fuller wording
  // as a save of its own — on a one-sense word too, where there's nothing to pick.
  const card = word.meaningZh ?? "";
  const cardTerms = terms(card).map((x) => x.toLowerCase());
  const previewTerms = new Set(terms(preview).map((x) => x.toLowerCase()));
  const fuller =
    picked.size > 0 && preview !== card && cardTerms.length > 0 && cardTerms.every((x) => previewTerms.has(x));
  const repicked = picked.size !== initial.size || [...picked].some((i) => !initial.has(i));
  const dirty = repicked || fuller;

  const save = useMutation({
    mutationFn: () => api.updateWord(word.id, { meaningZh: preview, senseIndexes: indexes }),
    onSuccess: (w) => {
      qc.setQueryData(["word", word.id], w);
      // The pick is what the card tests now — mirror it onto the cached senses so
      // the row stops offering to save what has just been saved.
      qc.setQueryData(sensesKey, {
        ...q.data,
        senses: senses.map((s, i) => ({ ...s, onCard: picked.has(i) })),
      });
      qc.invalidateQueries({ queryKey: ["words"] });
      show({ icon: "✓", title: t("word.meaningsSaved") });
    },
    onError: (e) => show({ icon: "⚠️", title: errText(e, t) }),
  });

  if (q.isPending)
    return (
      <div className="space-y-2">
        <p className="text-xs font-semibold uppercase tracking-[0.1em] text-ink-faint">{t("word.meanings")}</p>
        <Skeleton className="h-24 rounded-[18px]" />
        <p className="text-[12px] text-ink-faint">{t("word.meaningsLoading")}</p>
      </div>
    );

  if (!senses.length)
    return word.collocations.length > 0 ? (
      <TapGlossPills
        label={t("word.collocations")}
        items={word.collocations}
        sourceLang={word.sourceLang}
        targetLang={word.targetLang}
      />
    ) : null;

  const multi = senses.length > 1;
  const toggle = (i: number) =>
    setPicked((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i);
      else next.add(i);
      return next;
    });

  return (
    <div className="space-y-2">
      <p className="text-xs font-semibold uppercase tracking-[0.1em] text-ink-faint">{t("word.meanings")}</p>
      <ol className="overflow-hidden rounded-[18px] border border-black/[0.06] bg-surface">
        {senses.map((s, i) => {
          const on = picked.has(i);
          return (
            <li
              key={i}
              className={cn(
                "flex gap-3 border-black/[0.06] px-4 py-3.5 transition-colors sm:gap-4 sm:px-5 [&:not(:first-child)]:border-t",
                multi && on && "bg-sage-tint/35",
              )}
            >
              {multi && (
                <span
                  className={cn(
                    "mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-[13px] font-bold",
                    on ? "bg-sage text-white" : "bg-black/[0.05] text-ink-soft",
                  )}
                >
                  {i + 1}
                </span>
              )}
              <div className="min-w-0 flex-1">
                <div className="flex items-start justify-between gap-3">
                  <p className="min-w-0 leading-snug">
                    {s.pos && <span className="mr-2 text-[13px] italic text-ink-faint">{s.pos}</span>}
                    <span className={cn("text-[18px] font-semibold text-ink", tgtFont(word.targetLang))}>{s.meaning}</span>
                  </p>
                  {multi && (
                    <button
                      type="button"
                      onClick={() => toggle(i)}
                      aria-pressed={on}
                      className={cn(
                        "inline-flex shrink-0 items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold transition-colors",
                        on
                          ? "bg-sage text-white hover:bg-sage-deep"
                          : "border border-black/[0.1] text-ink-soft hover:border-sage/60 hover:text-sage-deep",
                      )}
                    >
                      {on ? <Check className="h-3 w-3" /> : <Plus className="h-3 w-3" />}
                      {on ? t("word.meaningsTested") : t("word.meaningsAdd")}
                    </button>
                  )}
                </div>
                {s.phrases.length > 0 && (
                  <ul className="mt-2 space-y-1.5 border-l-2 border-sage/30 pl-3">
                    {s.phrases.map((p, j) => (
                      <li key={j} className="leading-snug">
                        <span className={cn("text-[15px] text-ink", srcFont(word.sourceLang))}>{p.text}</span>
                        {showTr && p.reading && <span className="ml-2 text-[13px] text-ink-faint">{p.reading}</span>}
                        {p.translation && (
                          <span className={cn("block text-[13px] text-ink-soft", tgtFont(word.targetLang))}>
                            {p.translation}
                          </span>
                        )}
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            </li>
          );
        })}
      </ol>
      {(multi || fuller) && (
        <div className="flex flex-wrap items-center gap-x-3 gap-y-2">
          {dirty ? (
            <>
              <p className="min-w-0 text-[12px] text-ink-faint">
                {t("word.meaningsPreview")}{" "}
                <span className={cn("font-semibold text-ink-soft", tgtFont(word.targetLang))}>{preview || "—"}</span>
              </p>
              <button
                type="button"
                onClick={() => save.mutate()}
                disabled={picked.size === 0 || save.isPending}
                className="rounded-full bg-sage px-3.5 py-1.5 text-xs font-semibold text-white transition-colors hover:bg-sage-deep disabled:opacity-50"
              >
                {t(repicked ? "word.meaningsSave" : "word.meaningsFuller")}
              </button>
            </>
          ) : (
            <p className="text-[12px] text-ink-faint">{t("word.meaningsHint")}</p>
          )}
        </div>
      )}
      {/* The dictionary behind the senses. Its licence asks for the name and a link
          to the licence wherever the data appears, which is here. */}
      {credit && (
        <p className="text-[11px] text-ink-faint">
          <a
            href={credit.url}
            target="_blank"
            rel="noreferrer noopener"
            className="underline underline-offset-2 hover:text-ink-soft"
          >
            {credit.source}
          </a>
          {" · "}
          <a
            href={credit.licenseUrl}
            target="_blank"
            rel="noreferrer noopener"
            className="underline underline-offset-2 hover:text-ink-soft"
          >
            {credit.license}
          </a>
          {" — "}
          {t("word.meaningsSource")}
        </p>
      )}
    </div>
  );
}
