import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { normalizeHanzi } from "./hsk.js";

/**
 * CC-CEDICT as the sense inventory for Chinese words.
 *
 * The rule this file exists to enforce: **the dictionary owns the list of senses,
 * the model only picks and shortens one.** Three correctness bugs in three days
 * came from letting the model invent the inventory — «включить» produced only
 * 打开's "open" sense, though CC-CEDICT lists "to turn on" right there.
 *
 * Licensing shapes the storage. CC-CEDICT is CC BY-SA 4.0, so its data stays in
 * its own file (`data/cedict.jsonl`, generated by `scripts/build-cedict.mjs`),
 * is never written into our own generated text, and is credited in the app —
 * `cedictCredit()` feeds the line the word page shows. A raw entry is never
 * displayed: it goes into a prompt as the allowed inventory, and what the learner
 * reads is the model's short gloss of the sense it picked.
 *
 * Shipped as JSONL outside `src/` and read with `fs`, unlike the HSK list: 11k
 * entries as a TypeScript literal would be type-checked on every `tsc` run, and
 * `../../data` resolves the same from `src/services` and from `dist/services`,
 * so the build still copies nothing.
 */

export type CedictReading = { pinyin: string; glosses: string[] };
export type CedictEntry = { word: string; traditional?: string; readings: CedictReading[] };

type Row = { s: string; t?: string; r: { p: string; g: string[] }[] };
type Meta = { source: string; url: string; license: string; licenseUrl: string; release: string; words: number };

let index: Map<string, CedictEntry> | null = null;
let meta: Meta | null = null;

// Words asked for that the HSK subset doesn't hold — names, slang, whatever a
// textbook throws in. They fall back to the ungrounded path, and the count is
// the only evidence for whether the subset wants widening (see /api/admin/stats).
let hits = 0;
let misses = 0;

function build() {
  index = new Map();
  // `../../data` is the same directory from src/services and from dist/services.
  const path = fileURLToPath(new URL("../../data/cedict.jsonl", import.meta.url));
  let text: string;
  try {
    text = readFileSync(path, "utf8");
  } catch (err) {
    // A missing data file must not take card creation down with it: grounding is
    // an improvement over the model-only path, never a dependency of it.
    console.error("[cedict] no dictionary at", path, "— senses fall back to ungrounded", err);
    return;
  }
  for (const raw of text.split("\n")) {
    // Trimmed, not just split: git hands this file back with CRLF on a Windows
    // checkout, and a lone "\r" is a truthy line that JSON.parse throws on.
    const line = raw.trim();
    if (!line) continue;
    const row = JSON.parse(line) as Row & { _meta?: Meta };
    if (row._meta) {
      meta = row._meta;
      continue;
    }
    index.set(row.s, {
      word: row.s,
      ...(row.t ? { traditional: row.t } : {}),
      readings: row.r.map((r) => ({ pinyin: r.p, glosses: r.g })),
    });
  }
}

function idx() {
  if (!index) build();
  return index!;
}

/** The dictionary entry for a Chinese headword, or null when it is not in the subset. */
export function cedictLookup(word: string): CedictEntry | null {
  const hit = idx().get(normalizeHanzi(word)) ?? null;
  if (hit) hits++;
  else misses++;
  return hit;
}

/** Attribution — a licence condition, so the app shows it rather than just this file. */
export function cedictCredit() {
  if (!meta) build();
  return {
    source: meta?.source ?? "CC-CEDICT",
    url: meta?.url ?? "https://www.mdbg.net/chinese/dictionary?page=cc-cedict",
    license: meta?.license ?? "CC BY-SA 4.0",
    licenseUrl: meta?.licenseUrl ?? "https://creativecommons.org/licenses/by-sa/4.0/",
    release: meta?.release ?? "",
  };
}

/** How often the subset covers what learners actually add. */
export function cedictCoverage() {
  if (!index) build();
  return { words: index!.size, hits, misses };
}

/** Grounding only applies to Chinese headwords; everything else keeps the old path. */
export function isChinese(lang: string | null | undefined): boolean {
  return lang === "zh" || lang === "zh-Hant";
}

/**
 * The sense inventory as a prompt block, or null when the word isn't covered.
 * Readings stay separate — a headword with two of them (只 zhī / zhǐ) has two
 * genuinely different sense sets, and folding them together is how a card ends up
 * glossing the wrong one. Capped so a 9-sense entry can't crowd out the rest of
 * the prompt; the senses are already ordered by the dictionary.
 */
export function cedictInventory(word: string, maxGlosses = 12): string | null {
  const entry = cedictLookup(word);
  if (!entry) return null;
  const lines: string[] = [];
  let left = maxGlosses;
  for (const reading of entry.readings) {
    if (left <= 0) break;
    const glosses = reading.glosses.slice(0, left);
    left -= glosses.length;
    const head = entry.readings.length > 1 ? `[${reading.pinyin}] ` : "";
    lines.push(head + glosses.map((g, i) => `${i + 1}. ${g}`).join(" "));
  }
  return lines.join("\n");
}
