-- AlterTable
ALTER TABLE "Word" ADD COLUMN     "writeDifficulty" DOUBLE PRECISION,
ADD COLUMN     "writeDue" TIMESTAMP(3),
ADD COLUMN     "writeLapses" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "writeLast" TIMESTAMP(3),
ADD COLUMN     "writeReps" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "writeStability" DOUBLE PRECISION,
ADD COLUMN     "writeState" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "writeSteps" INTEGER NOT NULL DEFAULT 0;
